kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
cgroupDriver: systemd
kubernetesVersion: ${k_version}
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/etc/kubernetes/kubelet-plugins/volume/exec"
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock